--- #YAML:1.0
name:                Geo-Google-StaticMaps-V2
version:             0.05
abstract:            Generate Images from Google Static Maps API V2 API
license:             ~
author:              
    - Michael R. Davis (mdavis@stopllc.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Package::New:                  0
    Path::Class:                   0
    Test::Simple:                  0.44
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
